#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-Drunk
version:      0.01
version_from: lib/Acme/Drunk.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
